apiVersion: apps/v1
kind: Deployment
metadata:
  name: variantec-backend
  labels:
    app: variantec
    component: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: variantec
      component: backend
  template:
    metadata:
      labels:
        app: variantec
        component: backend
    spec:
      serviceAccountName: default
      containers:
      - name: backend
        image: gcr.io/waldher-zahnarzt/variantec-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        readinessProbe:
          httpGet:
            path: /api/bookings
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/bookings
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: variantec-backend
spec:
  selector:
    app: variantec
    component: backend
  ports:
  - port: 8080
    targetPort: 8080
