apiVersion: apps/v1
kind: Deployment
metadata:
  name: variantec-frontend
  labels:
    app: variantec
    component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: variantec
      component: frontend
  template:
    metadata:
      labels:
        app: variantec
        component: frontend
    spec:
      containers:
      - name: frontend
        image: gcr.io/waldher-zahnarzt/variantec-frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "/api"
---
apiVersion: v1
kind: Service
metadata:
  name: variantec-frontend
spec:
  selector:
    app: variantec
    component: frontend
  ports:
  - port: 80
    targetPort: 3000
