apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend.yaml
- frontend.yaml
- httproute.yaml
- healthcheckpolicy.yaml
images:
- name: gcr.io/waldher-zahnarzt/variantec-backend
  newName: gcr.io/waldher-zahnarzt/variantec-backend
  newTag: latest
- name: gcr.io/waldher-zahnarzt/variantec-frontend
  newName: gcr.io/waldher-zahnarzt/variantec-frontend
  newTag: latest
